const organicFarmingProducts = [
    {
        productId: 1,
        productName: "Organic Tomatoes",
        category: "Vegetables",
        price: 80,
        description: "Fresh and juicy organic tomatoes grown without pesticides.",
        availableUnit: "kg",
        sellerId: "S001",
        sellerName: "GreenFields Farm",
        farmLocation: "Assam, India",
        imageUrl: "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
        rating: 4.5,
    },
    {
        productId: 2,
        productName: "Raw Honey",
        category: "Beverages",
        price: 300,
        description: "Pure raw honey collected from sustainable bee farms.",
        availableUnit: "500g",
        sellerId: "S002",
        sellerName: "NatureHive Farms",
        farmLocation: "Uttarakhand, India",
        imageUrl: "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
        rating: 4.8,
    },
    {
        productId: 3,
        productName: "Organic Spinach",
        category: "Vegetables",
        price: 50,
        description: "Fresh organic spinach rich in nutrients.",
        availableUnit: "bunch",
        sellerId: "S001",
        sellerName: "GreenFields Farm",
        farmLocation: "Assam, India",
        imageUrl: "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
        rating: 4.6,
    },
    {
        productId: 4,
        productName: "Brown Rice",
        category: "Grains",
        price: 120,
        description: "Unpolished brown rice with high fiber content.",
        availableUnit: "kg",
        sellerId: "S003",
        sellerName: "HarvestWay Organics",
        farmLocation: "Punjab, India",
        imageUrl: "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
        rating: 4.7,
    },
    {
        productId: 5,
        productName: "Free-Range Eggs",
        category: "Dairy",
        price: 200,
        description: "Healthy and natural eggs from free-range hens.",
        availableUnit: "dozen",
        sellerId: "S004",
        sellerName: "SunnySide Farms",
        farmLocation: "Himachal Pradesh, India",
        imageUrl: "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
        rating: 4.9,
    },
    {
        productId: 6,
        productName: "Fresh Strawberries",
        category: "Fruits",
        price: 250,
        description: "Sweet and juicy organic strawberries.",
        availableUnit: "500g",
        sellerId: "S005",
        sellerName: "Berry Bliss Farms",
        farmLocation: "Maharashtra, India",
        imageUrl: "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
        rating: 4.6,
    },
    {
        productId: 7,
        productName: "Herbal Tea Leaves",
        category: "Beverages",
        price: 180,
        description: "Soothing herbal tea leaves for a healthy lifestyle.",
        availableUnit: "200g",
        sellerId: "S002",
        sellerName: "NatureHive Farms",
        farmLocation: "Uttarakhand, India",
        imageUrl: "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
        rating: 4.7,
    },
    {
        productId: 8,
        productName: "Organic Carrots",
        category: "Vegetables",
        price: 60,
        description: "Crunchy and sweet organic carrots.",
        availableUnit: "kg",
        sellerId: "S001",
        sellerName: "GreenFields Farm",
        farmLocation: "Assam, India",
        imageUrl: "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
        rating: 4.5,
    },
    {
        productId: 9,
        productName: "A2 Cow Milk",
        category: "Dairy",
        price: 80,
        description: "Pure A2 cow milk sourced from grass-fed cows.",
        availableUnit: "litre",
        sellerId: "S006",
        sellerName: "Pristine Dairy",
        farmLocation: "Rajasthan, India",
        imageUrl: "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
        rating: 4.9,
    },
    {
        productId: 10,
        productName: "Whole Wheat Flour",
        category: "Grains",
        price: 50,
        description: "Stone-ground whole wheat flour for healthy baking.",
        availableUnit: "kg",
        sellerId: "S003",
        sellerName: "HarvestWay Organics",
        farmLocation: "Punjab, India",
        imageUrl: "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
        rating: 4.8,
    },
    {
        productId: 11,
        productName: "Organic Mangoes",
        category: "Fruits",
        price: 150,
        description: "Sweet organic mangoes sourced from sustainable farms.",
        availableUnit: "kg",
        sellerId: "S007",
        sellerName: "Tropical Fresh Farms",
        farmLocation: "Karnataka, India",
        imageUrl: "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
        rating: 4.8,
    },
    {
        productId: 12,
        productName: "Organic Almonds",
        category: "Nuts",
        price: 750,
        description: "Premium organic almonds rich in nutrients.",
        availableUnit: "kg",
        sellerId: "S008",
        sellerName: "NutriFarms",
        farmLocation: "Haryana, India",
        imageUrl: "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
        rating: 4.7,
    },
    {
        productId: 13,
        productName: "Fresh Mint Leaves",
        category: "Herbs",
        price: 30,
        description: "Fragrant and fresh organic mint leaves.",
        availableUnit: "bunch",
        sellerId: "S009",
        sellerName: "Urban Herb Co.",
        farmLocation: "Delhi, India",
        imageUrl: "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
        rating: 4.5,
    },
    {
        productId: 14,
        productName: "Organic Coconut Oil",
        category: "Oils",
        price: 400,
        description: "Cold-pressed organic coconut oil for cooking and skincare.",
        availableUnit: "litre",
        sellerId: "S010",
        sellerName: "CocoPure Farms",
        farmLocation: "Kerala, India",
        imageUrl: "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
        rating: 4.9,
    },
    {
        productId: 15,
        productName: "Organic Potatoes",
        category: "Vegetables",
        price: 40,
        description: "Earthy and wholesome organic potatoes.",
        availableUnit: "kg",
        sellerId: "S001",
        sellerName: "GreenFields Farm",
        farmLocation: "Assam, India",
        imageUrl: "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
        rating: 4.6,
    },
    {
        productId: 16,
        productName: "Organic Chickpeas",
        category: "Legumes",
        price: 90,
        description: "Protein-rich organic chickpeas for healthy meals.",
        availableUnit: "kg",
        sellerId: "S011",
        sellerName: "PulsePure Farms",
        farmLocation: "Madhya Pradesh, India",
        imageUrl: "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
        rating: 4.7,
    },
    {
        productId: 17,
        productName: "Organic Apples",
        category: "Fruits",
        price: 200,
        description: "Crisp and sweet organic apples from Himalayan orchards.",
        availableUnit: "kg",
        sellerId: "S012",
        sellerName: "Apple Orchard Co.",
        farmLocation: "Himachal Pradesh, India",
        imageUrl: "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
        rating: 4.9,
    },
    {
        productId: 18,
        productName: "Organic Basil",
        category: "Herbs",
        price: 40,
        description: "Fresh organic basil leaves for aromatic cooking.",
        availableUnit: "bunch",
        sellerId: "S009",
        sellerName: "Urban Herb Co.",
        farmLocation: "Delhi, India",
        imageUrl: "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
        rating: 4.5,
    },
    {
        productId: 19,
        productName: "Organic Jaggery",
        category: "Sweeteners",
        price: 70,
        description: "Natural and healthy organic jaggery blocks.",
        availableUnit: "kg",
        sellerId: "S013",
        sellerName: "SweetEarth Farms",
        farmLocation: "Bihar, India",
        imageUrl: "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
        rating: 4.7,
    },
    {
        productId: 20,
        productName: "Organic Cashews",
        category: "Nuts",
        price: 850,
        description: "Crunchy and creamy organic cashews.",
        availableUnit: "kg",
        sellerId: "S008",
        sellerName: "NutriFarms",
        farmLocation: "Haryana, India",
        imageUrl: "https://example.com/images/cashews.jpg",
        rating: 4.5,
    },
    {
        productId: 21,
        productName: "Organic Turmeric Powder",
        category: "Spices",
        price: 150,
        description: "Premium organic turmeric powder with natural anti-inflammatory properties.",
        availableUnit: "500g",
        sellerId: "S014",
        sellerName: "SpiceGarden Organics",
        farmLocation: "Andhra Pradesh, India",
        imageUrl: "https://example.com/images/turmeric.jpg",
        rating: 4.8,
    },
    {
        productId: 22,
        productName: "Organic Avocados",
        category: "Fruits",
        price: 300,
        description: "Creamy organic avocados, perfect for guacamole or salads.",
        availableUnit: "kg",
        sellerId: "S015",
        sellerName: "Tropical Fresh Farms",
        farmLocation: "Karnataka, India",
        imageUrl: "https://example.com/images/avocados.jpg",
        rating: 4.9,
    },
    {
        productId: 23,
        productName: "Organic Lavender Oil",
        category: "Oils",
        price: 500,
        description: "Aromatic organic lavender oil for relaxation and skincare.",
        availableUnit: "100ml",
        sellerId: "S016",
        sellerName: "AromaPure Organics",
        farmLocation: "Tamil Nadu, India",
        imageUrl: "https://example.com/images/lavender-oil.jpg",
        rating: 4.8,
    },
    {
        productId: 24,
        productName: "Organic Peanuts",
        category: "Nuts",
        price: 180,
        description: "Crunchy and flavorful organic peanuts, perfect for snacking.",
        availableUnit: "kg",
        sellerId: "S017",
        sellerName: "NutriHarvest Farms",
        farmLocation: "Gujarat, India",
        imageUrl: "https://example.com/images/peanuts.jpg",
        rating: 4.6,
    },
    {
        productId: 25,
        productName: "Organic Broccoli",
        category: "Vegetables",
        price: 120,
        description: "Fresh organic broccoli, packed with nutrients and antioxidants.",
        availableUnit: "kg",
        sellerId: "S018",
        sellerName: "GreenLeaf Farms",
        farmLocation: "Himachal Pradesh, India",
        imageUrl: "https://example.com/images/broccoli.jpg",
        rating: 4.7,
    },
    {
        productId: 26,
        productName: "Organic Mustard Oil",
        category: "Oils",
        price: 350,
        description: "Cold-pressed organic mustard oil for cooking and massage.",
        availableUnit: "litre",
        sellerId: "S019",
        sellerName: "GoldenFields Organics",
        farmLocation: "West Bengal, India",
        imageUrl: "https://example.com/images/mustard-oil.jpg",
        rating: 4.8,
    },
]
export default organicFarmingProducts;